name: Scrape Tweets

on:
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run bot
        run: python bot.py
      - name: Commit scraped data
        run: |
          git config user.name "bot"
          git config user.email "bot@example.com"
          git add public/data.json
          git commit -m "Update data.json"
          git push
